//Generated by Agni.Clients.Tools.AgniGluecCompiler

/* Auto generated by Glue Client Compiler tool (gluec)
on 08.09.2017 18:36:32 at CRAZYROGUE by mad
Do not modify this file by hand if you plan to regenerate this file again by the tool as manual changes will be lost
*/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;

using NFX.Glue;
using NFX.Glue.Protocol;


namespace Agni.Social.Graph
{
// This implementation needs @Agni.@Social.@Graph.@IGraphNodeSystemClient, so
// it can be used with ServiceClientHub class

  ///<summary>
  /// Client for glued contract Agni.Social.Graph.IGraphNodeSystem server.
  /// Each contract method has synchronous and asynchronous versions, the later denoted by 'Async_' prefix.
  /// May inject client-level inspectors here like so:
  ///   client.MsgInspectors.Register( new YOUR_CLIENT_INSPECTOR_TYPE());
  ///</summary>
  public class GraphNodeSystemClient : ClientEndPoint, @Agni.@Social.@Graph.@IGraphNodeSystemClient
  {

  #region Static Members

     private static TypeSpec s_ts_CONTRACT;
     private static MethodSpec @s_ms_SaveNode_0;
     private static MethodSpec @s_ms_GetNode_1;
     private static MethodSpec @s_ms_DeleteNode_2;
     private static MethodSpec @s_ms_UndeleteNode_3;
     private static MethodSpec @s_ms_RemoveNode_4;

     //static .ctor
     static GraphNodeSystemClient()
     {
         var t = typeof(@Agni.@Social.@Graph.@IGraphNodeSystem);
         s_ts_CONTRACT = new TypeSpec(t);
         @s_ms_SaveNode_0 = new MethodSpec(t.GetMethod("SaveNode", new Type[]{ typeof(@Agni.@Social.@Graph.@GraphNode) }));
         @s_ms_GetNode_1 = new MethodSpec(t.GetMethod("GetNode", new Type[]{ typeof(@NFX.@DataAccess.@Distributed.@GDID) }));
         @s_ms_DeleteNode_2 = new MethodSpec(t.GetMethod("DeleteNode", new Type[]{ typeof(@NFX.@DataAccess.@Distributed.@GDID) }));
         @s_ms_UndeleteNode_3 = new MethodSpec(t.GetMethod("UndeleteNode", new Type[]{ typeof(@NFX.@DataAccess.@Distributed.@GDID) }));
         @s_ms_RemoveNode_4 = new MethodSpec(t.GetMethod("RemoveNode", new Type[]{ typeof(@NFX.@DataAccess.@Distributed.@GDID) }));
     }
  #endregion

  #region .ctor
     public GraphNodeSystemClient(string node, Binding binding = null) : base(node, binding) { ctor(); }
     public GraphNodeSystemClient(Node node, Binding binding = null) : base(node, binding) { ctor(); }
     public GraphNodeSystemClient(IGlue glue, string node, Binding binding = null) : base(glue, node, binding) { ctor(); }
     public GraphNodeSystemClient(IGlue glue, Node node, Binding binding = null) : base(glue, node, binding) { ctor(); }

     //common instance .ctor body
     private void ctor()
     {

     }

  #endregion

     public override Type Contract
     {
       get { return typeof(@Agni.@Social.@Graph.@IGraphNodeSystem); }
     }



  #region Contract Methods

         ///<summary>
         /// Synchronous invoker for  'Agni.Social.Graph.IGraphNodeSystem.SaveNode'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning '@Agni.@Social.@Graph.@GraphChangeStatus' or WrappedExceptionData instance.
         /// ClientCallException is thrown if the call could not be placed in the outgoing queue.
         /// RemoteException is thrown if the server generated exception during method execution.
         ///</summary>
         public @Agni.@Social.@Graph.@GraphChangeStatus @SaveNode(@Agni.@Social.@Graph.@GraphNode  @node)
         {
            var call = Async_SaveNode(@node);
            return call.GetValue<@Agni.@Social.@Graph.@GraphChangeStatus>();
         }

         ///<summary>
         /// Asynchronous invoker for  'Agni.Social.Graph.IGraphNodeSystem.SaveNode'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning no exception or WrappedExceptionData instance.
         /// CallSlot is returned that can be queried for CallStatus, ResponseMsg and result.
         ///</summary>
         public CallSlot Async_SaveNode(@Agni.@Social.@Graph.@GraphNode  @node)
         {
            var request = new RequestAnyMsg(s_ts_CONTRACT, @s_ms_SaveNode_0, false, RemoteInstance, new object[]{@node});
            return DispatchCall(request);
         }



         ///<summary>
         /// Synchronous invoker for  'Agni.Social.Graph.IGraphNodeSystem.GetNode'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning '@Agni.@Social.@Graph.@GraphNode' or WrappedExceptionData instance.
         /// ClientCallException is thrown if the call could not be placed in the outgoing queue.
         /// RemoteException is thrown if the server generated exception during method execution.
         ///</summary>
         public @Agni.@Social.@Graph.@GraphNode @GetNode(@NFX.@DataAccess.@Distributed.@GDID  @gNode)
         {
            var call = Async_GetNode(@gNode);
            return call.GetValue<@Agni.@Social.@Graph.@GraphNode>();
         }

         ///<summary>
         /// Asynchronous invoker for  'Agni.Social.Graph.IGraphNodeSystem.GetNode'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning no exception or WrappedExceptionData instance.
         /// CallSlot is returned that can be queried for CallStatus, ResponseMsg and result.
         ///</summary>
         public CallSlot Async_GetNode(@NFX.@DataAccess.@Distributed.@GDID  @gNode)
         {
            var request = new RequestAnyMsg(s_ts_CONTRACT, @s_ms_GetNode_1, false, RemoteInstance, new object[]{@gNode});
            return DispatchCall(request);
         }



         ///<summary>
         /// Synchronous invoker for  'Agni.Social.Graph.IGraphNodeSystem.DeleteNode'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning '@Agni.@Social.@Graph.@GraphChangeStatus' or WrappedExceptionData instance.
         /// ClientCallException is thrown if the call could not be placed in the outgoing queue.
         /// RemoteException is thrown if the server generated exception during method execution.
         ///</summary>
         public @Agni.@Social.@Graph.@GraphChangeStatus @DeleteNode(@NFX.@DataAccess.@Distributed.@GDID  @gNode)
         {
            var call = Async_DeleteNode(@gNode);
            return call.GetValue<@Agni.@Social.@Graph.@GraphChangeStatus>();
         }

         ///<summary>
         /// Asynchronous invoker for  'Agni.Social.Graph.IGraphNodeSystem.DeleteNode'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning no exception or WrappedExceptionData instance.
         /// CallSlot is returned that can be queried for CallStatus, ResponseMsg and result.
         ///</summary>
         public CallSlot Async_DeleteNode(@NFX.@DataAccess.@Distributed.@GDID  @gNode)
         {
            var request = new RequestAnyMsg(s_ts_CONTRACT, @s_ms_DeleteNode_2, false, RemoteInstance, new object[]{@gNode});
            return DispatchCall(request);
         }



         ///<summary>
         /// Synchronous invoker for  'Agni.Social.Graph.IGraphNodeSystem.UndeleteNode'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning '@Agni.@Social.@Graph.@GraphChangeStatus' or WrappedExceptionData instance.
         /// ClientCallException is thrown if the call could not be placed in the outgoing queue.
         /// RemoteException is thrown if the server generated exception during method execution.
         ///</summary>
         public @Agni.@Social.@Graph.@GraphChangeStatus @UndeleteNode(@NFX.@DataAccess.@Distributed.@GDID  @gNode)
         {
            var call = Async_UndeleteNode(@gNode);
            return call.GetValue<@Agni.@Social.@Graph.@GraphChangeStatus>();
         }

         ///<summary>
         /// Asynchronous invoker for  'Agni.Social.Graph.IGraphNodeSystem.UndeleteNode'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning no exception or WrappedExceptionData instance.
         /// CallSlot is returned that can be queried for CallStatus, ResponseMsg and result.
         ///</summary>
         public CallSlot Async_UndeleteNode(@NFX.@DataAccess.@Distributed.@GDID  @gNode)
         {
            var request = new RequestAnyMsg(s_ts_CONTRACT, @s_ms_UndeleteNode_3, false, RemoteInstance, new object[]{@gNode});
            return DispatchCall(request);
         }



         ///<summary>
         /// Synchronous invoker for  'Agni.Social.Graph.IGraphNodeSystem.RemoveNode'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning '@Agni.@Social.@Graph.@GraphChangeStatus' or WrappedExceptionData instance.
         /// ClientCallException is thrown if the call could not be placed in the outgoing queue.
         /// RemoteException is thrown if the server generated exception during method execution.
         ///</summary>
         public @Agni.@Social.@Graph.@GraphChangeStatus @RemoveNode(@NFX.@DataAccess.@Distributed.@GDID  @gNode)
         {
            var call = Async_RemoveNode(@gNode);
            return call.GetValue<@Agni.@Social.@Graph.@GraphChangeStatus>();
         }

         ///<summary>
         /// Asynchronous invoker for  'Agni.Social.Graph.IGraphNodeSystem.RemoveNode'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning no exception or WrappedExceptionData instance.
         /// CallSlot is returned that can be queried for CallStatus, ResponseMsg and result.
         ///</summary>
         public CallSlot Async_RemoveNode(@NFX.@DataAccess.@Distributed.@GDID  @gNode)
         {
            var request = new RequestAnyMsg(s_ts_CONTRACT, @s_ms_RemoveNode_4, false, RemoteInstance, new object[]{@gNode});
            return DispatchCall(request);
         }


  #endregion

  }//class
}//namespace
