//Generated by Agni.Clients.Tools.AgniGluecCompiler

/* Auto generated by Glue Client Compiler tool (gluec)
on 8/13/2017 3:50:49 PM at SEXTOD by Anton
Do not modify this file by hand if you plan to regenerate this file again by the tool as manual changes will be lost
*/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;

using NFX.Glue;
using NFX.Glue.Protocol;


namespace Agni.Social.Graph
{
// This implementation needs @Agni.@Social.@Graph.@IGraphFriendSystemClient, so
// it can be used with ServiceClientHub class

  ///<summary>
  /// Client for glued contract Agni.Social.Graph.IGraphFriendSystem server.
  /// Each contract method has synchronous and asynchronous versions, the later denoted by 'Async_' prefix.
  /// May inject client-level inspectors here like so:
  ///   client.MsgInspectors.Register( new YOUR_CLIENT_INSPECTOR_TYPE());
  ///</summary>
  public class GraphFriendSystemClient : ClientEndPoint, @Agni.@Social.@Graph.@IGraphFriendSystemClient
  {

  #region Static Members

     private static TypeSpec s_ts_CONTRACT;
     private static MethodSpec @s_ms_GetFriendLists_0;
     private static MethodSpec @s_ms_AddFriendList_1;
     private static MethodSpec @s_ms_DeleteFriendList_2;
     private static MethodSpec @s_ms_GetFriendConnections_3;
     private static MethodSpec @s_ms_AddFriend_4;
     private static MethodSpec @s_ms_AssignFriendLists_5;
     private static MethodSpec @s_ms_DeleteFriend_6;

     //static .ctor
     static GraphFriendSystemClient()
     {
         var t = typeof(@Agni.@Social.@Graph.@IGraphFriendSystem);
         s_ts_CONTRACT = new TypeSpec(t);
         @s_ms_GetFriendLists_0 = new MethodSpec(t.GetMethod("GetFriendLists", new Type[]{ typeof(@NFX.@DataAccess.@Distributed.@GDID) }));
         @s_ms_AddFriendList_1 = new MethodSpec(t.GetMethod("AddFriendList", new Type[]{ typeof(@NFX.@DataAccess.@Distributed.@GDID), typeof(@System.@String), typeof(@System.@String) }));
         @s_ms_DeleteFriendList_2 = new MethodSpec(t.GetMethod("DeleteFriendList", new Type[]{ typeof(@NFX.@DataAccess.@Distributed.@GDID), typeof(@System.@String) }));
         @s_ms_GetFriendConnections_3 = new MethodSpec(t.GetMethod("GetFriendConnections", new Type[]{ typeof(@Agni.@Social.@Graph.@FriendQuery) }));
         @s_ms_AddFriend_4 = new MethodSpec(t.GetMethod("AddFriend", new Type[]{ typeof(@NFX.@DataAccess.@Distributed.@GDID), typeof(@NFX.@DataAccess.@Distributed.@GDID), typeof(@System.@Nullable<@System.@Boolean>) }));
         @s_ms_AssignFriendLists_5 = new MethodSpec(t.GetMethod("AssignFriendLists", new Type[]{ typeof(@NFX.@DataAccess.@Distributed.@GDID), typeof(@NFX.@DataAccess.@Distributed.@GDID), typeof(@System.@String) }));
         @s_ms_DeleteFriend_6 = new MethodSpec(t.GetMethod("DeleteFriend", new Type[]{ typeof(@NFX.@DataAccess.@Distributed.@GDID), typeof(@NFX.@DataAccess.@Distributed.@GDID) }));
     }
  #endregion

  #region .ctor
     public GraphFriendSystemClient(string node, Binding binding = null) : base(node, binding) { ctor(); }
     public GraphFriendSystemClient(Node node, Binding binding = null) : base(node, binding) { ctor(); }
     public GraphFriendSystemClient(IGlue glue, string node, Binding binding = null) : base(glue, node, binding) { ctor(); }
     public GraphFriendSystemClient(IGlue glue, Node node, Binding binding = null) : base(glue, node, binding) { ctor(); }

     //common instance .ctor body
     private void ctor()
     {

     }

  #endregion

     public override Type Contract
     {
       get { return typeof(@Agni.@Social.@Graph.@IGraphFriendSystem); }
     }



  #region Contract Methods

         ///<summary>
         /// Synchronous invoker for  'Agni.Social.Graph.IGraphFriendSystem.GetFriendLists'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning '@System.@Collections.@Generic.@IEnumerable<@System.@String>' or WrappedExceptionData instance.
         /// ClientCallException is thrown if the call could not be placed in the outgoing queue.
         /// RemoteException is thrown if the server generated exception during method execution.
         ///</summary>
         public @System.@Collections.@Generic.@IEnumerable<@System.@String> @GetFriendLists(@NFX.@DataAccess.@Distributed.@GDID  @gNode)
         {
            var call = Async_GetFriendLists(@gNode);
            return call.GetValue<@System.@Collections.@Generic.@IEnumerable<@System.@String>>();
         }

         ///<summary>
         /// Asynchronous invoker for  'Agni.Social.Graph.IGraphFriendSystem.GetFriendLists'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning no exception or WrappedExceptionData instance.
         /// CallSlot is returned that can be queried for CallStatus, ResponseMsg and result.
         ///</summary>
         public CallSlot Async_GetFriendLists(@NFX.@DataAccess.@Distributed.@GDID  @gNode)
         {
            var request = new RequestAnyMsg(s_ts_CONTRACT, @s_ms_GetFriendLists_0, false, RemoteInstance, new object[]{@gNode});
            return DispatchCall(request);
         }



         ///<summary>
         /// Synchronous invoker for  'Agni.Social.Graph.IGraphFriendSystem.AddFriendList'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning '@Agni.@Social.@Graph.@GraphChangeStatus' or WrappedExceptionData instance.
         /// ClientCallException is thrown if the call could not be placed in the outgoing queue.
         /// RemoteException is thrown if the server generated exception during method execution.
         ///</summary>
         public @Agni.@Social.@Graph.@GraphChangeStatus @AddFriendList(@NFX.@DataAccess.@Distributed.@GDID  @gNode, @System.@String  @list, @System.@String  @description)
         {
            var call = Async_AddFriendList(@gNode, @list, @description);
            return call.GetValue<@Agni.@Social.@Graph.@GraphChangeStatus>();
         }

         ///<summary>
         /// Asynchronous invoker for  'Agni.Social.Graph.IGraphFriendSystem.AddFriendList'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning no exception or WrappedExceptionData instance.
         /// CallSlot is returned that can be queried for CallStatus, ResponseMsg and result.
         ///</summary>
         public CallSlot Async_AddFriendList(@NFX.@DataAccess.@Distributed.@GDID  @gNode, @System.@String  @list, @System.@String  @description)
         {
            var request = new RequestAnyMsg(s_ts_CONTRACT, @s_ms_AddFriendList_1, false, RemoteInstance, new object[]{@gNode, @list, @description});
            return DispatchCall(request);
         }



         ///<summary>
         /// Synchronous invoker for  'Agni.Social.Graph.IGraphFriendSystem.DeleteFriendList'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning '@Agni.@Social.@Graph.@GraphChangeStatus' or WrappedExceptionData instance.
         /// ClientCallException is thrown if the call could not be placed in the outgoing queue.
         /// RemoteException is thrown if the server generated exception during method execution.
         ///</summary>
         public @Agni.@Social.@Graph.@GraphChangeStatus @DeleteFriendList(@NFX.@DataAccess.@Distributed.@GDID  @gNode, @System.@String  @list)
         {
            var call = Async_DeleteFriendList(@gNode, @list);
            return call.GetValue<@Agni.@Social.@Graph.@GraphChangeStatus>();
         }

         ///<summary>
         /// Asynchronous invoker for  'Agni.Social.Graph.IGraphFriendSystem.DeleteFriendList'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning no exception or WrappedExceptionData instance.
         /// CallSlot is returned that can be queried for CallStatus, ResponseMsg and result.
         ///</summary>
         public CallSlot Async_DeleteFriendList(@NFX.@DataAccess.@Distributed.@GDID  @gNode, @System.@String  @list)
         {
            var request = new RequestAnyMsg(s_ts_CONTRACT, @s_ms_DeleteFriendList_2, false, RemoteInstance, new object[]{@gNode, @list});
            return DispatchCall(request);
         }



         ///<summary>
         /// Synchronous invoker for  'Agni.Social.Graph.IGraphFriendSystem.GetFriendConnections'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning '@System.@Collections.@Generic.@IEnumerable<@Agni.@Social.@Graph.@FriendConnection>' or WrappedExceptionData instance.
         /// ClientCallException is thrown if the call could not be placed in the outgoing queue.
         /// RemoteException is thrown if the server generated exception during method execution.
         ///</summary>
         public @System.@Collections.@Generic.@IEnumerable<@Agni.@Social.@Graph.@FriendConnection> @GetFriendConnections(@Agni.@Social.@Graph.@FriendQuery  @query)
         {
            var call = Async_GetFriendConnections(@query);
            return call.GetValue<@System.@Collections.@Generic.@IEnumerable<@Agni.@Social.@Graph.@FriendConnection>>();
         }

         ///<summary>
         /// Asynchronous invoker for  'Agni.Social.Graph.IGraphFriendSystem.GetFriendConnections'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning no exception or WrappedExceptionData instance.
         /// CallSlot is returned that can be queried for CallStatus, ResponseMsg and result.
         ///</summary>
         public CallSlot Async_GetFriendConnections(@Agni.@Social.@Graph.@FriendQuery  @query)
         {
            var request = new RequestAnyMsg(s_ts_CONTRACT, @s_ms_GetFriendConnections_3, false, RemoteInstance, new object[]{@query});
            return DispatchCall(request);
         }



         ///<summary>
         /// Synchronous invoker for  'Agni.Social.Graph.IGraphFriendSystem.AddFriend'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning '@Agni.@Social.@Graph.@GraphChangeStatus' or WrappedExceptionData instance.
         /// ClientCallException is thrown if the call could not be placed in the outgoing queue.
         /// RemoteException is thrown if the server generated exception during method execution.
         ///</summary>
         public @Agni.@Social.@Graph.@GraphChangeStatus @AddFriend(@NFX.@DataAccess.@Distributed.@GDID  @gNode, @NFX.@DataAccess.@Distributed.@GDID  @gFriendNode, @System.@Nullable<@System.@Boolean>  @approve)
         {
            var call = Async_AddFriend(@gNode, @gFriendNode, @approve);
            return call.GetValue<@Agni.@Social.@Graph.@GraphChangeStatus>();
         }

         ///<summary>
         /// Asynchronous invoker for  'Agni.Social.Graph.IGraphFriendSystem.AddFriend'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning no exception or WrappedExceptionData instance.
         /// CallSlot is returned that can be queried for CallStatus, ResponseMsg and result.
         ///</summary>
         public CallSlot Async_AddFriend(@NFX.@DataAccess.@Distributed.@GDID  @gNode, @NFX.@DataAccess.@Distributed.@GDID  @gFriendNode, @System.@Nullable<@System.@Boolean>  @approve)
         {
            var request = new RequestAnyMsg(s_ts_CONTRACT, @s_ms_AddFriend_4, false, RemoteInstance, new object[]{@gNode, @gFriendNode, @approve});
            return DispatchCall(request);
         }



         ///<summary>
         /// Synchronous invoker for  'Agni.Social.Graph.IGraphFriendSystem.AssignFriendLists'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning '@Agni.@Social.@Graph.@GraphChangeStatus' or WrappedExceptionData instance.
         /// ClientCallException is thrown if the call could not be placed in the outgoing queue.
         /// RemoteException is thrown if the server generated exception during method execution.
         ///</summary>
         public @Agni.@Social.@Graph.@GraphChangeStatus @AssignFriendLists(@NFX.@DataAccess.@Distributed.@GDID  @gNode, @NFX.@DataAccess.@Distributed.@GDID  @gFriendNode, @System.@String  @lists)
         {
            var call = Async_AssignFriendLists(@gNode, @gFriendNode, @lists);
            return call.GetValue<@Agni.@Social.@Graph.@GraphChangeStatus>();
         }

         ///<summary>
         /// Asynchronous invoker for  'Agni.Social.Graph.IGraphFriendSystem.AssignFriendLists'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning no exception or WrappedExceptionData instance.
         /// CallSlot is returned that can be queried for CallStatus, ResponseMsg and result.
         ///</summary>
         public CallSlot Async_AssignFriendLists(@NFX.@DataAccess.@Distributed.@GDID  @gNode, @NFX.@DataAccess.@Distributed.@GDID  @gFriendNode, @System.@String  @lists)
         {
            var request = new RequestAnyMsg(s_ts_CONTRACT, @s_ms_AssignFriendLists_5, false, RemoteInstance, new object[]{@gNode, @gFriendNode, @lists});
            return DispatchCall(request);
         }



         ///<summary>
         /// Synchronous invoker for  'Agni.Social.Graph.IGraphFriendSystem.DeleteFriend'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning '@Agni.@Social.@Graph.@GraphChangeStatus' or WrappedExceptionData instance.
         /// ClientCallException is thrown if the call could not be placed in the outgoing queue.
         /// RemoteException is thrown if the server generated exception during method execution.
         ///</summary>
         public @Agni.@Social.@Graph.@GraphChangeStatus @DeleteFriend(@NFX.@DataAccess.@Distributed.@GDID  @gNode, @NFX.@DataAccess.@Distributed.@GDID  @gFriendNode)
         {
            var call = Async_DeleteFriend(@gNode, @gFriendNode);
            return call.GetValue<@Agni.@Social.@Graph.@GraphChangeStatus>();
         }

         ///<summary>
         /// Asynchronous invoker for  'Agni.Social.Graph.IGraphFriendSystem.DeleteFriend'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning no exception or WrappedExceptionData instance.
         /// CallSlot is returned that can be queried for CallStatus, ResponseMsg and result.
         ///</summary>
         public CallSlot Async_DeleteFriend(@NFX.@DataAccess.@Distributed.@GDID  @gNode, @NFX.@DataAccess.@Distributed.@GDID  @gFriendNode)
         {
            var request = new RequestAnyMsg(s_ts_CONTRACT, @s_ms_DeleteFriend_6, false, RemoteInstance, new object[]{@gNode, @gFriendNode});
            return DispatchCall(request);
         }


  #endregion

  }//class
}//namespace
