//Generated by Agni.Clients.Tools.AgniGluecCompiler

/* Auto generated by Glue Client Compiler tool (gluec)
on 5/19/2017 8:47:54 PM at CNONIM-PC by cnonim
Do not modify this file by hand if you plan to regenerate this file again by the tool as manual changes will be lost
*/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;

using NFX.Glue;
using NFX.Glue.Protocol;


namespace Agni.Clients
{
// This implementation needs @Agni.@Contracts.@IGDIDPersistenceRemoteLocationClient, so
// it can be used with ServiceClientHub class

  ///<summary>
  /// Client for glued contract Agni.Contracts.IGDIDPersistenceRemoteLocation server.
  /// Each contract method has synchronous and asynchronous versions, the later denoted by 'Async_' prefix.
  /// May inject client-level inspectors here like so:
  ///   client.MsgInspectors.Register( new YOUR_CLIENT_INSPECTOR_TYPE());
  ///</summary>
  public class GDIDPersistenceRemoteLocation : ClientEndPoint, @Agni.@Contracts.@IGDIDPersistenceRemoteLocationClient
  {

  #region Static Members

     private static TypeSpec s_ts_CONTRACT;
     private static MethodSpec @s_ms_Read_0;
     private static MethodSpec @s_ms_Write_1;

     //static .ctor
     static GDIDPersistenceRemoteLocation()
     {
         var t = typeof(@Agni.@Contracts.@IGDIDPersistenceRemoteLocation);
         s_ts_CONTRACT = new TypeSpec(t);
         @s_ms_Read_0 = new MethodSpec(t.GetMethod("Read", new Type[]{ typeof(@System.@Byte), typeof(@System.@String), typeof(@System.@String) }));
         @s_ms_Write_1 = new MethodSpec(t.GetMethod("Write", new Type[]{ typeof(@System.@String), typeof(@System.@String), typeof(@NFX.@DataAccess.@Distributed.@GDID) }));
     }
  #endregion

  #region .ctor
     public GDIDPersistenceRemoteLocation(string node, Binding binding = null) : base(node, binding) { ctor(); }
     public GDIDPersistenceRemoteLocation(Node node, Binding binding = null) : base(node, binding) { ctor(); }
     public GDIDPersistenceRemoteLocation(IGlue glue, string node, Binding binding = null) : base(glue, node, binding) { ctor(); }
     public GDIDPersistenceRemoteLocation(IGlue glue, Node node, Binding binding = null) : base(glue, node, binding) { ctor(); }

     //common instance .ctor body
     private void ctor()
     {

     }

  #endregion

     public override Type Contract
     {
       get { return typeof(@Agni.@Contracts.@IGDIDPersistenceRemoteLocation); }
     }



  #region Contract Methods

         ///<summary>
         /// Synchronous invoker for  'Agni.Contracts.IGDIDPersistenceRemoteLocation.Read'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning '@System.@Nullable<@NFX.@DataAccess.@Distributed.@GDID>' or WrappedExceptionData instance.
         /// ClientCallException is thrown if the call could not be placed in the outgoing queue.
         /// RemoteException is thrown if the server generated exception during method execution.
         ///</summary>
         public @System.@Nullable<@NFX.@DataAccess.@Distributed.@GDID> @Read(@System.@Byte  @authority, @System.@String  @sequenceName, @System.@String  @scopeName)
         {
            var call = Async_Read(@authority, @sequenceName, @scopeName);
            return call.GetValue<@System.@Nullable<@NFX.@DataAccess.@Distributed.@GDID>>();
         }

         ///<summary>
         /// Asynchronous invoker for  'Agni.Contracts.IGDIDPersistenceRemoteLocation.Read'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning no exception or WrappedExceptionData instance.
         /// CallSlot is returned that can be queried for CallStatus, ResponseMsg and result.
         ///</summary>
         public CallSlot Async_Read(@System.@Byte  @authority, @System.@String  @sequenceName, @System.@String  @scopeName)
         {
            var request = new RequestAnyMsg(s_ts_CONTRACT, @s_ms_Read_0, false, RemoteInstance, new object[]{@authority, @sequenceName, @scopeName});
            return DispatchCall(request);
         }



         ///<summary>
         /// Synchronous invoker for  'Agni.Contracts.IGDIDPersistenceRemoteLocation.Write'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning no exception or WrappedExceptionData instance.
         /// ClientCallException is thrown if the call could not be placed in the outgoing queue.
         /// RemoteException is thrown if the server generated exception during method execution.
         ///</summary>
         public void @Write(@System.@String  @sequenceName, @System.@String  @scopeName, @NFX.@DataAccess.@Distributed.@GDID  @value)
         {
            var call = Async_Write(@sequenceName, @scopeName, @value);
            call.CheckVoidValue();
         }

         ///<summary>
         /// Asynchronous invoker for  'Agni.Contracts.IGDIDPersistenceRemoteLocation.Write'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning no exception or WrappedExceptionData instance.
         /// CallSlot is returned that can be queried for CallStatus, ResponseMsg and result.
         ///</summary>
         public CallSlot Async_Write(@System.@String  @sequenceName, @System.@String  @scopeName, @NFX.@DataAccess.@Distributed.@GDID  @value)
         {
            var request = new RequestAnyMsg(s_ts_CONTRACT, @s_ms_Write_1, false, RemoteInstance, new object[]{@sequenceName, @scopeName, @value});
            return DispatchCall(request);
         }


  #endregion

  }//class
}//namespace
