//Generated by Agni.Clients.Tools.AgniGluecCompiler

/* Auto generated by Glue Client Compiler tool (gluec)
on 6/28/2017 12:01:46 AM at CNONIM-PC by cnonim
Do not modify this file by hand if you plan to regenerate this file again by the tool as manual changes will be lost
*/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;

using NFX.Glue;
using NFX.Glue.Protocol;


namespace Agni.Clients
{
// This implementation needs @Agni.@Contracts.@ITelemetryReceiverClient, so
// it can be used with ServiceClientHub class

  ///<summary>
  /// Client for glued contract Agni.Contracts.ITelemetryReceiver server.
  /// Each contract method has synchronous and asynchronous versions, the later denoted by 'Async_' prefix.
  /// May inject client-level inspectors here like so:
  ///   client.MsgInspectors.Register( new YOUR_CLIENT_INSPECTOR_TYPE());
  ///</summary>
  public class TelemetryReceiver : ClientEndPoint, @Agni.@Contracts.@ITelemetryReceiverClient
  {

  #region Static Members

     private static TypeSpec s_ts_CONTRACT;
     private static MethodSpec @s_ms_SendDatums_0;

     //static .ctor
     static TelemetryReceiver()
     {
         var t = typeof(@Agni.@Contracts.@ITelemetryReceiver);
         s_ts_CONTRACT = new TypeSpec(t);
         @s_ms_SendDatums_0 = new MethodSpec(t.GetMethod("SendDatums", new Type[]{ typeof(@NFX.@Instrumentation.@Datum[]) }));
     }
  #endregion

  #region .ctor
     public TelemetryReceiver(string node, Binding binding = null) : base(node, binding) { ctor(); }
     public TelemetryReceiver(Node node, Binding binding = null) : base(node, binding) { ctor(); }
     public TelemetryReceiver(IGlue glue, string node, Binding binding = null) : base(glue, node, binding) { ctor(); }
     public TelemetryReceiver(IGlue glue, Node node, Binding binding = null) : base(glue, node, binding) { ctor(); }

     //common instance .ctor body
     private void ctor()
     {

     }

  #endregion

     public override Type Contract
     {
       get { return typeof(@Agni.@Contracts.@ITelemetryReceiver); }
     }



  #region Contract Methods

         ///<summary>
         /// Synchronous invoker for  'Agni.Contracts.ITelemetryReceiver.SendDatums'.
         /// This is a one-way call per contract specification, meaning - the server sends no acknowledgement of this call receipt and
         /// there is no result that server could return back to the caller.
         /// ClientCallException is thrown if the call could not be placed in the outgoing queue.
         ///</summary>
         public void @SendDatums(@NFX.@Instrumentation.@Datum[]  @data)
         {
            var call = Async_SendDatums(@data);
            if (call.CallStatus != CallStatus.Dispatched)
                throw new ClientCallException(call.CallStatus, "Call failed: 'TelemetryReceiver.SendDatums'");
         }

         ///<summary>
         /// Asynchronous invoker for  'Agni.Contracts.ITelemetryReceiver.SendDatums'.
         /// This is a one-way call per contract specification, meaning - the server sends no acknowledgement of this call receipt and
         /// there is no result that server could return back to the caller.
         /// CallSlot is returned that can be queried for CallStatus, ResponseMsg.
         ///</summary>
         public CallSlot Async_SendDatums(@NFX.@Instrumentation.@Datum[]  @data)
         {
            var request = new @Agni.@Contracts.@RequestMsg_ITelemetryReceiver_SendDatums(s_ts_CONTRACT, @s_ms_SendDatums_0, true, RemoteInstance)
            {
               MethodArg_0_data = @data,
            };
            return DispatchCall(request);
         }


  #endregion

  }//class
}//namespace
