//Generated by Agni.Clients.Tools.AgniGluecCompiler

/* Auto generated by Glue Client Compiler tool (gluec)
on 4/5/2017 7:30:44 PM at CNONIM-PC by cnonim
Do not modify this file by hand if you plan to regenerate this file again by the tool as manual changes will be lost
*/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;

using NFX.Glue;
using NFX.Glue.Protocol;


namespace Agni.Clients
{
// This implementation needs @Agni.@Contracts.@IZoneHostReplicatorClient, so
// it can be used with ServiceClientHub class

  ///<summary>
  /// Client for glued contract Agni.Contracts.IZoneHostReplicator server.
  /// Each contract method has synchronous and asynchronous versions, the later denoted by 'Async_' prefix.
  /// May inject client-level inspectors here like so:
  ///   client.MsgInspectors.Register( new YOUR_CLIENT_INSPECTOR_TYPE());
  ///</summary>
  public class ZoneHostReplicator : ClientEndPoint, @Agni.@Contracts.@IZoneHostReplicatorClient
  {

  #region Static Members

     private static TypeSpec s_ts_CONTRACT;
     private static MethodSpec @s_ms_PostDynamicHostInfo_0;
     private static MethodSpec @s_ms_GetDynamicHostInfo_1;
     private static MethodSpec @s_ms_PostHostInfo_2;

     //static .ctor
     static ZoneHostReplicator()
     {
         var t = typeof(@Agni.@Contracts.@IZoneHostReplicator);
         s_ts_CONTRACT = new TypeSpec(t);
         @s_ms_PostDynamicHostInfo_0 = new MethodSpec(t.GetMethod("PostDynamicHostInfo", new Type[]{ typeof(@Agni.@Contracts.@DynamicHostID), typeof(@System.@DateTime), typeof(@System.@String), typeof(@System.@Int32) }));
         @s_ms_GetDynamicHostInfo_1 = new MethodSpec(t.GetMethod("GetDynamicHostInfo", new Type[]{ typeof(@Agni.@Contracts.@DynamicHostID) }));
         @s_ms_PostHostInfo_2 = new MethodSpec(t.GetMethod("PostHostInfo", new Type[]{ typeof(@Agni.@Contracts.@HostInfo), typeof(@System.@Nullable<@Agni.@Contracts.@DynamicHostID>) }));
     }
  #endregion

  #region .ctor
     public ZoneHostReplicator(string node, Binding binding = null) : base(node, binding) { ctor(); }
     public ZoneHostReplicator(Node node, Binding binding = null) : base(node, binding) { ctor(); }
     public ZoneHostReplicator(IGlue glue, string node, Binding binding = null) : base(glue, node, binding) { ctor(); }
     public ZoneHostReplicator(IGlue glue, Node node, Binding binding = null) : base(glue, node, binding) { ctor(); }

     //common instance .ctor body
     private void ctor()
     {

     }

  #endregion

     public override Type Contract
     {
       get { return typeof(@Agni.@Contracts.@IZoneHostReplicator); }
     }



  #region Contract Methods

         ///<summary>
         /// Synchronous invoker for  'Agni.Contracts.IZoneHostReplicator.PostDynamicHostInfo'.
         /// This is a one-way call per contract specification, meaning - the server sends no acknowledgement of this call receipt and
         /// there is no result that server could return back to the caller.
         /// ClientCallException is thrown if the call could not be placed in the outgoing queue.
         ///</summary>
         public void @PostDynamicHostInfo(@Agni.@Contracts.@DynamicHostID  @id, @System.@DateTime  @stamp, @System.@String  @owner, @System.@Int32  @votes)
         {
            var call = Async_PostDynamicHostInfo(@id, @stamp, @owner, @votes);
            if (call.CallStatus != CallStatus.Dispatched)
                throw new ClientCallException(call.CallStatus, "Call failed: 'ZoneHostReplicator.PostDynamicHostInfo'");
         }

         ///<summary>
         /// Asynchronous invoker for  'Agni.Contracts.IZoneHostReplicator.PostDynamicHostInfo'.
         /// This is a one-way call per contract specification, meaning - the server sends no acknowledgement of this call receipt and
         /// there is no result that server could return back to the caller.
         /// CallSlot is returned that can be queried for CallStatus, ResponseMsg.
         ///</summary>
         public CallSlot Async_PostDynamicHostInfo(@Agni.@Contracts.@DynamicHostID  @id, @System.@DateTime  @stamp, @System.@String  @owner, @System.@Int32  @votes)
         {
            var request = new @Agni.@Contracts.@RequestMsg_IZoneHostReplicator_PostDynamicHostInfo(s_ts_CONTRACT, @s_ms_PostDynamicHostInfo_0, true, RemoteInstance)
            {
               MethodArg_0_id = @id,
               MethodArg_1_stamp = @stamp,
               MethodArg_2_owner = @owner,
               MethodArg_3_votes = @votes,
            };
            return DispatchCall(request);
         }



         ///<summary>
         /// Synchronous invoker for  'Agni.Contracts.IZoneHostReplicator.GetDynamicHostInfo'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning '@Agni.@Contracts.@DynamicHostInfo' or WrappedExceptionData instance.
         /// ClientCallException is thrown if the call could not be placed in the outgoing queue.
         /// RemoteException is thrown if the server generated exception during method execution.
         ///</summary>
         public @Agni.@Contracts.@DynamicHostInfo @GetDynamicHostInfo(@Agni.@Contracts.@DynamicHostID  @hid)
         {
            var call = Async_GetDynamicHostInfo(@hid);
            return call.GetValue<@Agni.@Contracts.@DynamicHostInfo>();
         }

         ///<summary>
         /// Asynchronous invoker for  'Agni.Contracts.IZoneHostReplicator.GetDynamicHostInfo'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning no exception or WrappedExceptionData instance.
         /// CallSlot is returned that can be queried for CallStatus, ResponseMsg and result.
         ///</summary>
         public CallSlot Async_GetDynamicHostInfo(@Agni.@Contracts.@DynamicHostID  @hid)
         {
            var request = new RequestAnyMsg(s_ts_CONTRACT, @s_ms_GetDynamicHostInfo_1, false, RemoteInstance, new object[]{@hid});
            return DispatchCall(request);
         }



         ///<summary>
         /// Synchronous invoker for  'Agni.Contracts.IZoneHostReplicator.PostHostInfo'.
         /// This is a one-way call per contract specification, meaning - the server sends no acknowledgement of this call receipt and
         /// there is no result that server could return back to the caller.
         /// ClientCallException is thrown if the call could not be placed in the outgoing queue.
         ///</summary>
         public void @PostHostInfo(@Agni.@Contracts.@HostInfo  @host, @System.@Nullable<@Agni.@Contracts.@DynamicHostID>  @hid)
         {
            var call = Async_PostHostInfo(@host, @hid);
            if (call.CallStatus != CallStatus.Dispatched)
                throw new ClientCallException(call.CallStatus, "Call failed: 'ZoneHostReplicator.PostHostInfo'");
         }

         ///<summary>
         /// Asynchronous invoker for  'Agni.Contracts.IZoneHostReplicator.PostHostInfo'.
         /// This is a one-way call per contract specification, meaning - the server sends no acknowledgement of this call receipt and
         /// there is no result that server could return back to the caller.
         /// CallSlot is returned that can be queried for CallStatus, ResponseMsg.
         ///</summary>
         public CallSlot Async_PostHostInfo(@Agni.@Contracts.@HostInfo  @host, @System.@Nullable<@Agni.@Contracts.@DynamicHostID>  @hid)
         {
            var request = new RequestAnyMsg(s_ts_CONTRACT, @s_ms_PostHostInfo_2, true, RemoteInstance, new object[]{@host, @hid});
            return DispatchCall(request);
         }


  #endregion

  }//class
}//namespace
