using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Reflection;

using NFX;
using NFX.Environment;
using NFX.Glue;
using NFX.Glue.Tools;

/*
 Usage pattern:
   gluec Agni.dll -c "Agni.Clients.Tools.AgniGluecCompiler, Agni" -o ns-suffix="" cl-suffix="" ns-root="Agni.Clients"
*/


namespace Agni.Clients.Tools
{
  public sealed class AgniGluecCompiler : CSharpGluecCompiler
  {
    public AgniGluecCompiler(Assembly asm) : base(asm) {}


    protected override string FileHeader()
    {
      return
@"//Generated by {0}
{1}".Args( GetType().FullName, base.FileHeader() );
    }

    protected override void BeforeClientClass(StringBuilder sb, Type tc, string cname, string iname)
    {
      sb.AppendLine("// This implementation needs {0}, so".Args(iname));
      sb.AppendLine("// it can be used with ServiceClientHub class");
      sb.AppendLine();
    }

    protected override string GetClientInterfaceName(Type tc)
    {
      return TypeToStr(tc) + "Client";
    }

  }
}
